IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = 'Products')
BEGIN
	CREATE DATABASE Products;
END
GO

USE Products;
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'Products')
BEGIN
CREATE TABLE Products
(
	ProductID INT PRIMARY KEY,
	ProductName VARCHAR(100) NOT NULL,
	Price DECIMAL(10, 2) NOT NULL,
	Quantity INT NOT NULL

);
END
GO